application: test
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_files: static
  upload: favicon\.ico

- url: /images
  static_dir: images
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
